apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "generate.labels" . | nindent 4 }}
  name: {{ include "generate.fullname" . }}
type: Opaque
stringData:
  promtail.yaml: |
{{ include "promtail.config" . | indent 4 }}
