apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "generate.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "generate.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.server.httpPort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- else }}
      nodePort: null
      {{- end }}
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.server.grpcPort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.grpcNodePort)) }}
      nodePort: {{ .Values.service.grpcNodePort }}
      {{- else }}
      nodePort: null
      {{- end }}
    {{- if .Values.syslog.listen }}
    - name: syslog
      protocol: UDP
      port: {{ .Values.service.syslogPort }}
      targetPort: {{ .Values.syslog.port }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.syslogNodePort)) }}
      nodePort: {{ .Values.service.syslogNodePort }}
      {{- else }}
      nodePort: null
      {{- end }}
    {{- end }}
  selector:
    {{- include "generate.selectorLabels" . | nindent 4 }}
  {{- if and (.Capabilities.APIVersions.Has "discovery.k8s.io/v1beta1/EndpointSlice") (.Values.service.topology) }}
  topologyKeys:
    {{- toYaml .Values.service.topologyKeys | nindent 4 }}
  {{- end }}
