apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeName: efs-pv
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi