apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-terraform
spec:
  consolidation:
    enabled: true
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["on-demand"]
    - key: "kubernetes.io/arch" # If not included, the webhook for the AWS Cloud Provider will default to amd64
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3a.medium"] #["r5a.xlarge", "r5a.large", "m5a.large", "m5a.xlarge"]       
  # taints:
  # - key: node.kubernetes.io/disk-pressure
  #   value: "true"
  #   effect: "NoSchedule"
  limits:
    resources:
      cpu: 1000                               # optional, recommended to limit total provisioned CPUs
      memory: 1000Gi
  provider:
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3                           # optional, recommended to use instead of `provider`
    securityGroupSelector:
      aws-ids: "sg-0f5da1dfa1669175d"
    subnetSelector:
      aws-ids: "subnet-03ade4859f845df0b,subnet-097a0d21fc496c65e,subnet-0e00363b25a7c5edf"
  # ttlSecondsAfterEmpty: 30                    # optional, but never scales down if not set
  ttlSecondsUntilExpired: 2592000