# Empty values file

description: Library chart

# --- Supported values

## nameOverride -- Overrides the chart name
#nameOverride: ""
## fullnameOverride -- Overrides the full name
#fullnameOverride: ""
#
## --- Pod and container configuration
##
#image:
#  # image.repository -- Overrides the image repository
#  repository: "chart-name"
#  # image.tag -- Overrides the image tag whose default is the chart appVersion.
#  tag: ""
#
#deploymentType: Deployment
#
### Horizontal Pod Autoscaler
### ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
#autoscaling:
#  # autoscaling.enabled -- Specifies the horizontal pod autoscaling is enabled
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 80
#
### PodDisruptionBudget
### ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
#pdb:
#  # pdb.enabled -- Specifies whether a pod disruption budget should be created
#  enabled: false
#
#  # pdb.minAvailable -- Description of the number of pods from that set that must still be available after the eviction
#  # minAvailable: 1
#
#  # pdb.minAvailable -- Description of the number of pods from that set that can be unavailable after the eviction
#  # maxUnavailable: 0
#
#serviceAccount:
#  # serviceAccount.create -- Specifies whether a service account should be created
#  create: true
#
#  # serviceAccount.annotations -- Annotations to add to the service account
#  annotations: {}
#
#  # serviceAccount.labels -- Labels to add to the service account
#  labels: {}
#
#  # serviceAccount.name -- The name of the service account to use.
#  # If not set and create is true, a name is generated using the fullname template
#  name: ""
#
### Ingress settings
#ingress:
#  # ingress.enabled -- Specifies whether a ingress should be created
#  enabled: true
#
#  className: ""
#
#  tls: []
#    # - secretName: chart-example-tls
#    #   hosts:
#    #     - chart-template.example.com
#
#  hosts:
#    - host: chart-template.example.com
#      paths:
#        - /
#        # - /docs
#        # - /api
#
#  labels: {}
#  annotations: {}
#    # kubernetes.io/ingress.class
#    # ingress.kubernetes.io/browser-xss-filter: 'true'
#    # ingress.kubernetes.io/content-type-nosniff: 'true'
#    # ingress.kubernetes.io/ssl-redirect: 'true'
#    # ingress.kubernetes.io/ssl-temporary-redirect: 'true'
#    # kubernetes.io/tls-acme: 'true'
#    # cert-manager.io/cluster-issuer: letsencrypt-prod
#
## Create NetworkPolicy
## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
#networkPolicy:
#  # networkPolicy.enabled -- Specifies whether a NetworkPolicy should be created
#  enabled: false
#  # networkPolicy.labels -- Additional labels for NetworkPolicy
#  labels: {}
#  # networkPolicy.annotations -- Annotations for NetworkPolicy
#  annotations: {}
#
#  # networkPolicy.ingress -- Ingress rules
#  ingress:
#    - {}
#    # - from:
#    #     - ipBlock:
#    #         cidr: 172.17.0.0/16
#    #         except:
#    #         - 172.17.1.0/24
#    #     - namespaceSelector:
#    #         matchLabels:
#    #           project: myproject
#    #     - podSelector:
#    #         matchLabels:
#    #           role: frontend
#    #     - podSelector:
#    #         matchLabels:
#    #           app: bookstore
#    #           role: api
#    #   ports:
#    #     - protocol: TCP
#    #       port: 6379
#
#  # networkPolicy.egress -- Egress rules
#  egress:
#    - {}
#    # - to:
#    #     - ipBlock:
#    #         cidr: 10.0.0.0/24
#    #   ports:
#    #     - protocol: TCP
#    #       port: 5978
#
