apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "generate.labels" . | nindent 4 }}
  name: {{ printf "%s-pods" (include "generate.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    {{- include "generate.selectorLabels" . | nindent 4 }}
  ports: []
  clusterIP: None
  type: ClusterIP
