{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "generate.labels" . | nindent 4 }}
  name: {{ include "generate.rbacName" . }}
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - nodes
      - nodes/proxy
      - services
      - pods
      - pods/log
    verbs:
      - get
      - watch
      - list
  {{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups:
      - policy
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "generate.pspName" . }}
  {{- end }}
{{- end -}}
