{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "generate.labels" . | nindent 4 }}
  name: {{ include "generate.rbacName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "generate.rbacName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "generate.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
